ALTER TABLE tasks ADD COLUMN prompt TEXT;
ALTER TABLE tasks ADD COLUMN output TEXT;
ALTER TABLE tasks ADD COLUMN revision_count INTEGER DEFAULT 0;
ALTER TABLE tasks ADD COLUMN parent_task_id INTEGER REFERENCES tasks(id) ON DELETE SET NULL;
